### PR TITLE
Add swift package description

### LINKED ISSUE #7: Add a Package.swift file for swift package manager?
It would be nice to be able to include this as an external dependency using swift package manager.

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR proposes changes to address the issue identified in #7 by adding a Swift Package description, and a basic GitHub Actions test workflow for this package.

Fixes #7.

### CODE REVIEW

**Comment by tonyarnold** [comment]
You could very nearly drop the Xcode project entirely here - your call, Mr G.

**Comment by mattgallagher** [comment]
Hi @tonyarnold, thanks for this. I'll look this over and merge it on the weekend. Crazy week ;-)

**Comment by mattgallagher** [comment]
Aagh. The old problem of "if I don't do something immediately I'll forget it entirely". I've *finally* merged this. Thanks, Tony.

**Comment by tonyarnold** [comment]
All good, Matt. Thanks for accepting the changes 😀

**Comment by tonyarnold** [comment]
Oh, one other thing - it might be worth tagging a release (even if it's a pre-release version number), so that there's something for people to target.

**Pull request merged**
